version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: medical_appointments_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointments_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: